name: Deploy to VM

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.VM_SSH_KEY }}

    - name: Deploy to VM
      run: |
        ssh -o StrictHostKeyChecking=no azureuser@20.235.245.88 << 'EOF'
          cd /home/azureuser/flask-hello-world
          git pull origin master
          sudo systemctl daemon-reload
          sudo systemctl restart flask-hello-world.service
          sudo systemctl status flask-hello-world.service
          exit
        EOF
