name: Deploy to VM

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code with full depth
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Set up Git user
      run: |
        git config --global user.email "shinchanexperimentsingithub@gmail.com"
        git config --global user.name "JananiDhayalan"

    - name: Stash local changes if any
      run: git stash || true

    - name: Pull latest changes
      run: |
        git fetch origin master
        git merge FETCH_HEAD || true

    - name: Apply stashed changes if any
      run: git stash pop || true

    - name: Execute commands on the server
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.VM_HOST }}
        username: ${{ secrets.VM_USERNAME }}
        key: ${{ secrets.PRIVATE_KEY }}
        script: |
          cd /home/azureuser/flask-hello-world
          ls -a
          git config --global user.email "shinchanexperimentsingithub@gmail.com"
          git config --global user.name "JananiDhayalan"
          git add .
          git commit -m "Committing all local changes"
          git pull origin
          sudo systemctl daemon-reload
          sudo systemctl restart flask-hello-world.service
          sudo systemctl status flask-hello-world.service
          curl http://127.0.0.1:5000
